#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-0 -d 1 2 3
bspc monitor DP-2 -d 4 5 6
bspc monitor HDMI-0 -d 7 8 9

bspc config normal_border_color \#000000
bspc config active_border_color \#000000
bspc config focused_border_color \#734bab

bspc config border_width         4
bspc config window_gap          15

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle	 true

# Focus on mouse hover
bspc config focus_follows_pointer true

bspc rule -a Screenkey manage=off

bspc desktop -f 4

#########
# Mouse #
#########

# Modifier
bspc config pointer_modifier mod1

# Resize with alt and right click
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

$HOME/.config/polybar/launch.sh

