#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-2 -d 1 2 3
bspc monitor DP-0 -d 4 5 6
bspc monitor HDMI-0 -d 7 8 9

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Focus on mouse hover
bspc config focus_follows_pointer true

bspc rule -a Gimp state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc desktop -f 4

#########
# Mouse #
#########

# Modifier
bspc config pointer_modifier mod1

# Move with alt and left click
bspc config pointer_action1 move

# Resize with alt and richt click
# bspc config pointer_action2 resize_side

# Resize with alt and right click
bspc config pointer_action2 resize_corner

bspc config pointer_modifier mod1
bspc config pointer_action1 move
# bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner
